[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[rpc_endpoints]
sepolia = "${ETHEREUM_RPC_URL}"
mainnet = "${ETHEREUM_RPC_URL}"
bnb_testnet = "${BNB_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

